// <auto-generated />
namespace BooklyProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class added_imageUrl_in_Admin_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_imageUrl_in_Admin_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "202502191709320_added_imageUrl_in_Admin_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
